/* GENERATED by registry/patch_impact.py -- do not edit by hand.
 * (Initial vanilla-only seed authored in the generator's exact format; the
 * first patch-impact run regenerates this file and `--check` guards drift.)
 *
 * One entry per known ROM image. `gated_pcs` lists the dispatch entry PCs
 * whose original asm the patch rewrote (range overlap + transitive-callee
 * closure, DELEG-exempt); rom_ident.c maps them to table slots at init.
 * Only the exact proof-base image (FF4 JP rev 1.1) is `is_vanilla` -- other
 * clean revisions (e.g. JP rev 1.0) are deliberately UNKNOWN: the native
 * bodies were never proven against their bytes. */

#include "rom_profiles.h"
#include <stddef.h>

/* FF4 J2e EN v3.21: 67 gated of the dispatch table (see registry/patch_impact.py report). */
static const uint32_t k_gated_j2e_en_v321[] = {
    0x00808Eu, 0x00883Du, 0x00885Eu, 0x00AA58u, 0x00AAD8u, 0x00AB13u,
    0x00C0C4u, 0x00C3BDu, 0x00CB5Fu, 0x00FFBCu, 0x00FFE0u, 0x01CA85u,
    0x01DFD2u, 0x02A491u, 0x02DDDCu, 0x038009u, 0x088690u, 0x0E8B3Cu,
    0x12E35Bu, 0x12E613u, 0x12E7D3u, 0x12EB47u, 0x12EC06u, 0x12EC3Eu,
    0x12ED1Du, 0x12EE1Cu, 0x12EE25u, 0x12EE35u, 0x13BFE3u, 0x13C11Fu,
    0x14F626u, 0x14F63Eu, 0x14F6D6u, 0x14F796u, 0x1585ABu, 0x1589EDu,
    0x158B2Au, 0x158E05u, 0x158E57u, 0x158F34u, 0x159104u, 0x1591CAu,
    0x159204u, 0x1599FBu, 0x159B5Bu, 0x15AF24u, 0x15B09Cu, 0x15B6F1u,
    0x16C59Au, 0x16C8BCu, 0x16CB05u, 0x16CB72u, 0x16CFC4u, 0x16CFD0u,
    0x16D263u, 0x16D342u, 0x16D36Du, 0x16D831u, 0x16DBBEu, 0x16DBD2u,
    0x16DE1Bu, 0x16DF53u, 0x16F533u, 0x16F922u, 0x16FB93u, 0x16FFABu,
    0x1EA03Eu,
};

const ff4_rom_profile_t ff4_rom_profiles[] = {
    {
        /* Final Fantasy IV (Japan) rev 1.1, unheadered -- the proof base. */
        .crc32 = 0xCAA15E97u,
        .name = "FF4 JP 1.1 (vanilla)",
        .is_vanilla = 1,
        .gated_pcs = NULL,
        .gated_count = 0,
    },
    {
        .crc32 = 0xF135CAE6u,
        .name = "FF4 J2e EN v3.21",
        .is_vanilla = 0,
        .gated_pcs = k_gated_j2e_en_v321,
        .gated_count = 67,
    },
};

const int ff4_rom_profile_count =
    (int)(sizeof(ff4_rom_profiles) / sizeof(ff4_rom_profiles[0]));
