/* ROM identification + dispatch-profile arming (translation-patch ADR).
 *
 * The dispatch table's native C bodies were proven equivalent against ONE
 * exact ROM (FF4 JP rev 1.1, CRC32 CAA15E97). Translation patches produce
 * variant images whose code partially diverges from that proof base, so at
 * ff4_init the loaded image is identified by full-file CRC32 and the
 * matching profile (rom_profiles.c, generated by registry/patch_impact.py)
 * gates the affected dispatch slots back to the interpreter -- which reads
 * the patched bytes and is therefore always correct.
 *
 * Policy on an UNKNOWN image is the caller's (main.c):
 *   - device builds define FF4_REQUIRE_KNOWN_ROM and refuse to boot it; the
 *     scaffold reads the accessors below to render the refusal screen;
 *   - desktop builds warn and run it with the native dispatch fully
 *     disabled (pure interpreter -- slow but correct), which is how a
 *     foreign-lineage ROM (e.g. a US-base hack) stays usable for study. */

#ifndef FF4_ROM_IDENT_H
#define FF4_ROM_IDENT_H

#include <stdint.h>

typedef enum {
    FF4_ROM_VANILLA = 0,       /* the proof-base ROM: full native dispatch  */
    FF4_ROM_KNOWN_VARIANT = 1, /* profiled patch variant: partial gating    */
    FF4_ROM_UNKNOWN = 2,       /* no profile: never trust the native bodies */
} ff4_rom_ident_t;

/* Identify `rom` and arm the dispatch gate accordingly. Called by ff4_init
 * BEFORE snes_loadRom (the image may still be refused). Safe to call again
 * on a different image (re-arms from scratch). */
ff4_rom_ident_t ff4_rom_identify(const uint8_t *rom, int length);

/* Post-identify accessors (scaffold refusal screen / desktop banner). */
ff4_rom_ident_t ff4_rom_ident(void);
uint32_t ff4_rom_ident_crc32(void);
const char *ff4_rom_ident_name(void); /* profile name, or "unknown ROM" */

#endif /* FF4_ROM_IDENT_H */
