/* ROM-variant dispatch profiles -- see rom_ident.h and the translation-patch
 * ADR. rom_profiles.c is GENERATED by registry/patch_impact.py from the
 * per-routine range analysis of each patch; do not edit it by hand. */

#ifndef FF4_ROM_PROFILES_H
#define FF4_ROM_PROFILES_H

#include <stdint.h>

typedef struct {
    uint32_t crc32;           /* full-file CRC32 of the canonical image     */
    const char *name;         /* short human label (refusal screen, logs)   */
    int is_vanilla;           /* 1 = the proof-base ROM itself              */
    const uint32_t *gated_pcs;/* dispatch entry PCs to gate; NULL when none */
    int gated_count;
} ff4_rom_profile_t;

extern const ff4_rom_profile_t ff4_rom_profiles[];
extern const int ff4_rom_profile_count;

#endif /* FF4_ROM_PROFILES_H */
